# Generated by Django 6.1 on 2026-08-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='banquet_images',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='bar_images',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='fssai_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='gst_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='inside_view',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='outside_view',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pan_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rooftop_images',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='room_images',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='table_images',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
    ]
