# Generated by Django 6.1 on 2026-08-20 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('space_type', models.CharField(choices=[('table', 'Dining Table'), ('room', 'Hotel Room'), ('banquet', 'Banquet Hall'), ('rooftop', 'Rooftop Space'), ('bar', 'Bar Seating')], default='table', max_length=50)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('price_per_slot', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='restaurants.restaurant')),
            ],
        ),
    ]
