# Generated by Django 6.1 on 2026-08-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_homedeliveryorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spaces/'),
        ),
    ]
