# Generated by Django 6.1 on 2026-08-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_space_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_accepting_orders',
            field=models.BooleanField(default=True),
        ),
    ]
