# Generated by Django 6.1 on 2026-08-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_booking_extra_bed_booking_name_booking_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout',
            field=models.DateField(blank=True, null=True),
        ),
    ]
