# Generated by Django 6.1 on 2026-08-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_booking_checkin_booking_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='Paid', max_length=50),
        ),
    ]
